platform :ios, '11.0'

workspace 'CardBrandChoice.xcworkspace'

target 'CardBrandChoice' do
  project 'CardBrandChoice.xcodeproj'

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sample
  pod 'Stripe'
  pod 'DropDown'
end